spring.application.name=campus-goods-trading-platform
server.port=8080

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/campus_goods_trade?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB

app.upload-dir=uploads
